name: cli_res_venv
channels:
  - defaults
dependencies:
  - _libgcc_mutex 
  - _openmp_mutex 
  - ca-certificates 
  - certifi 
  - ld_impl_linux-64 
  - libffi 
  - libgcc-ng 
  - libgomp 
  - libstdcxx-ng 
  - ncurses 
  - openssl 
  - pip 
  - python 
  - readline 
  - setuptools 
  - sqlite 
  - tk 
  - tzdata 
  - wheel 
  - xz 
  - zlib 
  - pip:
    - anyio 
    - argon2-cffi 
    - argon2-cffi-bindings 
    - asttokens 
    - attrs 
    - babel 
    - backcall 
    - black 
    - bleach 
    - bqplot 
    - branca 
    - cffi 
    - charset-normalizer 
    - click 
    - colour 
    - cycler 
    - debugpy 
    - decorator 
    - defusedxml 
    - entrypoints 
    - executing 
    - folium 
    - fonttools 
    - geojson 
    - googledrivedownloader 
    - here-map-widget-for-jupyter 
    - idna 
    - ipyevents 
    - ipyfilechooser 
    - ipykernel 
    - ipyleaflet 
    - ipython 
    - ipython-genutils 
    - ipytree 
    - ipywidgets 
    - jedi 
    - jinja2 
    - json5 
    - jsonschema 
    - jupyter-client 
    - jupyter-core 
    - jupyter-server 
    - jupyterlab 
    - jupyterlab-pygments 
    - jupyterlab-server 
    - jupyterlab-widgets 
    - kiwisolver 
    - leafmap 
    - markupsafe 
    - matplotlib 
    - matplotlib-inline 
    - mistune 
    - mss 
    - mypy-extensions 
    - nbclassic 
    - nbclient 
    - nbconvert 
    - nbformat 
    - nest-asyncio 
    - notebook 
    - numpy 
    - owslib 
    - packaging 
    - palettable 
    - pandas 
    - pandocfilters 
    - parso 
    - pathspec 
    - pexpect 
    - pickleshare 
    - pillow 
    - platformdirs 
    - plotly 
    - prometheus-client 
    - prompt-toolkit 
    - ptyprocess 
    - pure-eval 
    - pycparser 
    - pycrs 
    - pygments 
    - pyparsing 
    - pyproj 
    - pyrsistent 
    - pyshp 
    - pystac 
    - pystac-client 
    - python-box 
    - python-dateutil 
    - pytz 
    - pyyaml 
    - pyzmq 
    - requests 
    - send2trash 
    - six 
    - sniffio 
    - stack-data 
    - tenacity 
    - terminado 
    - testpath 
    - tomli 
    - tornado 
    - tqdm 
    - traitlets 
    - traittypes 
    - typing-extensions 
    - urllib3 
    - wcwidth 
    - webencodings 
    - websocket-client 
    - whitebox 
    - whiteboxgui 
    - widgetsnbextension 
    - xyzservices 
