<<<<<<< HEAD
version: 0.3.1
=======
version: 0.3.0
>>>>>>> d6d0af71cccd5bd933d1ceb27d0c1305f3b5c993

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
